// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACmfF5qgHIulCaxjkUoLbX6b7SQP914nE',
    appId: '1:337357862033:web:78d8538c318e62145e3b30',
    messagingSenderId: '337357862033',
    projectId: 'burgercrown-39114',
    authDomain: 'burgercrown-39114.firebaseapp.com',
    storageBucket: 'burgercrown-39114.appspot.com',
    measurementId: 'G-53Y9TKDLCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApSdqU9YSzZtvInPEDqabKId2KnkjmRPs',
    appId: '1:337357862033:android:bc279aa7d417d6325e3b30',
    messagingSenderId: '337357862033',
    projectId: 'burgercrown-39114',
    storageBucket: 'burgercrown-39114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdB5bzG-Vu85Mw7M2uNMJtGFw6PEgheM0',
    appId: '1:337357862033:ios:dd7102d932ef3eca5e3b30',
    messagingSenderId: '337357862033',
    projectId: 'burgercrown-39114',
    storageBucket: 'burgercrown-39114.appspot.com',
    iosBundleId: 'com.example.burgerCrown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdB5bzG-Vu85Mw7M2uNMJtGFw6PEgheM0',
    appId: '1:337357862033:ios:dd7102d932ef3eca5e3b30',
    messagingSenderId: '337357862033',
    projectId: 'burgercrown-39114',
    storageBucket: 'burgercrown-39114.appspot.com',
    iosBundleId: 'com.example.burgerCrown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACmfF5qgHIulCaxjkUoLbX6b7SQP914nE',
    appId: '1:337357862033:web:1e86581538119a615e3b30',
    messagingSenderId: '337357862033',
    projectId: 'burgercrown-39114',
    authDomain: 'burgercrown-39114.firebaseapp.com',
    storageBucket: 'burgercrown-39114.appspot.com',
    measurementId: 'G-8RLB6QE372',
  );
}
